version: 2

builds:
  - id: client
    main: ./cmd/main.go
    binary: client
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

changelog:
  use: github
  sort: asc
  abbrev: -1

release:
  prerelease: auto
